repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v16.0.0'
  hooks:
  - id: clang-format
    exclude: |
        (?x)^(
            .*/.pio/.*|
            .*\.proto|
            .*\.json|
            .*\.js
        )$
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.15.0
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [--fix]
    # Run the formatter.
    - id: ruff-format
