name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: svelte/package-lock.json
      - name: Install Svelte Dependencies
        run: |
          cd svelte
          npm ci
      - name: Build Svelte Web UI
        run: ./build-svelte.sh
      - name: Install license-header-checker
        run: |
          curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - name: Setup secrets for build
        run: cp secrets.ini.example secrets.ini && cp local.ini.example local.ini
      - name: Run Quality Checks and Tests
        run: ./util/check.sh
      - name: Build PlatformIO Project
        run: pio run
